'use strict';

var locations = {
  "oswego" : {
    "office_name": "Oswego",
    "street_address_line_1": "384 East River Road",
    "city": "Oswego",
    "state": "NY",
    "zip_code": "13126",
    "mon_start": "9:00 AM",
    "mon_end": "4:45 PM",
    "tue_start": "9:00 AM",
    "tue_end": "4:45 PM",
    "wed_start": "9:00 AM",
    "wed_end": "4:45 PM",
    "thur_start": "9:00 AM",
    "thur_end": "4:45 PM",
    "fri_start": "9:00 AM",
    "fri_end": "4:45 PM",
    "longitude": "-76.483322",
    "latitude": "43.431512",
  },
  "niagara falls" : {
    "office_name": "Niagara Falls",
    "street_address_line_1": "1001 11th Street",
    "city": "Niagara Falls",
    "state": "NY",
    "zip_code": "14301",
    "mon_start": "9:00 AM",
    "mon_end": "4:30 PM",
    "tue_start": "9:00 AM",
    "tue_end": "4:30 PM",
    "wed_start": "9:00 AM",
    "wed_end": "6:30 PM",
    "thur_start": "9:00 AM",
    "thur_end": "4:30 PM",
    "fri_start": "9:00 AM",
    "fri_end": "4:30 PM",
    "longitude": "-79.049357",
    "latitude": "43.098766",
  },
  "belmont" : {
    "office_name": "Belmont",
    "street_address_line_1": "7 Court Street",
    "city": "Belmont",
    "state": "NY",
    "zip_code": "14813",
    "mon_start": "9:00 AM",
    "mon_end": "5:00 PM",
    "tue_start": "9:00 AM",
    "tue_end": "5:00 PM",
    "wed_start": "9:00 AM",
    "wed_end": "5:00 PM",
    "thur_start": "9:00 AM",
    "thur_end": "5:00 PM",
    "fri_start": "9:00 AM",
    "fri_end": "5:00 PM",
    "longitude": "-78.033519",
    "latitude": "42.224775",
  },
  "greece" : {
    "office_name": "Greece",
    "street_address_line_1": "152 Greece Ridge Center",
    "city": "Rochester",
    "state": "NY",
    "zip_code": "14626",
    "mon_start": "8:30 AM",
    "mon_end": "4:30 PM",
    "tue_start": "8:30 AM",
    "tue_end": "6:30 PM",
    "wed_start": "8:30 AM",
    "wed_end": "4:30 PM",
    "thur_start": "8:30 AM",
    "thur_end": "4:30 PM",
    "fri_start": "8:30 AM",
    "fri_end": "4:30 PM",
    "longitude": "-77.69635",
    "latitude": "43.204861",
  },
  "deposit" : {
    "office_name": "Deposit",
    "street_address_line_1": "3 Elm Street",
    "city": "Deposit",
    "state": "NY",
    "zip_code": "13754",
    "mon_start": "8:30 AM",
    "mon_end": "4:15 PM",
    "tue_start": "8:30 AM",
    "tue_end": "4:15 PM",
    "wed_start": "8:30 AM",
    "wed_end": "4:15 PM",
    "thur_start": "8:30 AM",
    "thur_end": "4:15 PM",
    "fri_start": "8:30 AM",
    "fri_end": "4:15 PM",
    "longitude": "-75.420874",
    "latitude": "42.061989",
  },
  "" : {
    "office_name": "",
    "street_address_line_1": "",
    "city": "",
    "state": "",
    "zip_code": "",
    "mon_start": "",
    "mon_end": "",
    "tue_start": "",
    "tue_end": "",
    "wed_start": "",
    "wed_end": "",
    "thur_start": "",
    "thur_end": "",
    "fri_start": "",
    "fri_end": "",
    "longitude": "",
    "latitude": "",
  }
};
